[package]
name = "rcli"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["QiaoPengjun <qiaopengjun0@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
